server:
  port: 9999
spring:
  security:
    user:
      password: password
  application:
    name: assignment-service
  h2:
    console:
      enabled: true
  datasource:
    url:  jdbc:h2:~/test;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE       

facebook:
  client:
    clientId: --replace me--
    clientSecret: --replace me--
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
    
hystrix:
 command:
  getAPIData:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds=10000     
