app:
 gateway:
  service-url: http://localhost:5555/services/

spring:
  security:
    user:
      password: password
  application:
    name: service-client
 
 
  datasource:
    url:  jdbc:mysql://192.168.99.100:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Appian6$
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  
debug: true  


facebook:
  client:
    clientId: 2127139123983127
    clientSecret: 8fd801cb21daa2cfbef9236398f18c2c
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
    
hystrix:
 command:
  getAPIData:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds=10000     
