app:
 gateway:
  service-url: https://gateway-service-140837.cfapps.io/services/

spring:
  security:
    user:
      password: password
  
 
 
  datasource:
    url:  jdbc:mysql://191.168.99.100:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Appian6$
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  
debug: true  


facebook:
  client:
    clientId: --replace me--
    clientSecret: --replace me--
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
    
hystrix:
 command:
  getAPIData:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds=10000     
