server:
  port: 5555
  servlet:
    context-path: /services
security:
  oauth2:
    resource:
      user-info-uri: https://graph.facebook.com/me   

zuul:
  routes:
    employee:
      path: /employee/**
      serviceId: employee-service-140837

hystrix:
  command:
    employee-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000                    

eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.application_uris[0]}
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url}
  #instance:
   # instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}} 